version: "3.9"

services:
    deliverycx_ikko:
        container_name: development_ikko
        env_file:
            - ./.production.env
        build:
            context: ./
        networks:
          - mynetwork
    rabbitmq:
      image: rabbitmq:management
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=540193
      ports:
        - "5672:5672"
        - "15672:15672"
      depends_on:
         - deliverycx_ikko
      networks:
        - mynetwork    
networks:
  mynetwork:
    external:
      name: delivglobalnetwork             