version: "3.9"

services:
    deliverycx_ikko:
        container_name: development_ikko
        env_file:
            - /.production.env
        depends_on:
            - redis
        build:
            context: ./server
        networks:
          - mynetwork
        links:
            - redis
    rabbitmq:
      image: rabbitmq
      volumes:
        - rabbit_data:/var/lib/rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - deliverycx_ikko         
networks:
  mynetwork:
    external:
      name: delivglobalnetwork             