version: "3.9"

services:
    deliverycx_ikko:
        container_name: development_ikko
        env_file:
            - ./.production.env
        build:
            context: ./
        restart: unless-stopped
        networks:
          - mynetwork
    redis:
        image: redis
        container_name: redis_ikko
        command:
            - "redis-server"
            - "--loglevel ${REDIS_LOGLEVEL:-warning}"
            - "--databases 2"
            - "--save 900 1"
            - "--save 300 10"
            - "--save 60 10000"
        volumes:
            - ./redis/data:/data
    rabbitmq:
      image: rabbitmq:management
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - "5672:5672"
        - "15672:15672"
      depends_on:
         - deliverycx_ikko
      networks:
        - mynetwork    
networks:
  mynetwork:
    external:
      name: delivglobalnetwork             